{% set name = "cymem" %}
{% set version = "2.0.4" %}
{% set sha256sum = "2baabeb408e4aaa0f51d7f6d8c53dd05f56decf34fb3f1f3180abe8755815890" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - patches/0001-remove-setup_requires.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  skip: True  # [win32 or linux32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python

test:
  requires:
    - pytest

about:
  home: https://github.com/explosion/cymem
  license: MIT
  license_file: LICENSE
  summary: Manage calls to calloc/free through Cython
  description: |
    cymem provides two small memory-management helpers for Cython. They make it
    easy to tie memory to a Python object’s life-cycle, so that the memory is
    freed when the object is garbage collected.
extra:
  recipe-maintainers:
    - rmax
    - h-vetinari
    - ines
    - honnibal
    - adrianeboyd
