{% set name = "cymem" %}
{% set version = "2.0.2" %}
{% set sha256sum = "ab88b1534f06df07262d9bc5efb3ba07948cdbe9a363eb9eaa4ad42fae6c7b5e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    # setup.py has wheel entry for setup_requires
    - wheel >=0.32.0,<0.33.0
  build:
    - {{ compiler('cxx') }}
  run:
    - python

test:
  requires:
    - pytest

about:
  home: https://github.com/explosion/cymem
  license: MIT
  license_file: LICENSE
  summary: Manage calls to calloc/free through Cython
  description: |
    cymem provides two small memory-management helpers for Cython. They make it
    easy to tie memory to a Python object’s life-cycle, so that the memory is
    freed when the object is garbage collected.
  doc_url: https://pypi.python.org/pypi/cymem
  doc_source_url: https://github.com/explosion/cymem/blob/master/README.rst
  dev_url: https://github.com/explosion/cymem

extra:
  recipe-maintainers:
    - rmax
