travis:
  secure:
    BINSTAR_TOKEN: YK77KJJJqUyI2ikRYzKJr+OgWm8hbQ+oGugoNz5ZBJvdNOEWZ/vXUKBRb8lOqIvb7FVf25aUBnyodE4t8V3FYA9FvwKRR7M8RkG1mJEiHWoqPrhF6UTlsBZ7GFGt+dZMmbyoEqZkpsyU6JbJtPYjK0kX7dvXdODW7FL8W7TRtBjRLAUcYqizduHO9q19ApCJPDz+Xs3D9RliXt8Y62WfpEwtwQgW7GtQ/V+RkJ2eUEGSTIiPTnAdTr1H3LXSGcO5P0atxpLSH9Y9bO9aoPJYGZVXM60hk1sTRM/qMYfwzK6yBm5PN/iAhQHTS1LuZg4UDh2VO6QXR2eVXn+ZfTeVVMpMPLWgBgVCKwwaHlCZhyLFyue47x6sdF5ziCB4Dc9dxmKzaBeTz/UHnWsPtiift65Ie0jYOtusdT/BDtwRpSaTzUbMhDGY4Rde5tnTiLV4jQzrDEXYzASQDv+9rpEkhuY1stRyJQvC7iVFx+4OzjIB20h5ksZW4CNdFXxE4EQSg5VbvIy5XzLbLCFvmO3d2jOQYDiYPaX0j/O0pKo7a7UFaYWLDOqVIwre9IsosKpE38KAWWEjuTISSrd33ojexm23mL+vXNHi/FHFmqKxe1gSPVyPK5Fvm4SUMopjwOq4qsshq16XdWPCDzpJIiUZ7cuFMu24YJRYHWWsyAhggUI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
