travis:
  secure:
    BINSTAR_TOKEN: nt3c9EamTbuqypY9T7JhyVNNcw9kUxhh9/8sxaiLBve+buRaKJ9Apx4pvRE3ZVJFXiPPyFuVeWfglOe3rqyeg0Sb73KvTgJ73rdkowLOhBSQXmBLgkWLJPGSIsIb8ZJG0yQGIlslEB9mVJazUZdQ/FUOWxYdT9WhZ8MFh0ryRxfao0CnPMDTVhQwlYnJ02+6te9ZXgn8aZjH4KpX6bcCgjX27Ks9+HahXwFLpd3re74z6iCwLrdgHzCj92mNvVcKAq2bU3MGq5nxrDXcxa53mZg65tPh4ph2q5ETRYnz6RA14RmoFR1kObkVdCoHwY+dOWTp1buIddYb6n/D9stO0+ea36ni0JoRYw1oajZPushj349nowLK/3kvWAJMxc4c5Fcb1W4GaCgZwdcs6gdsYc0qYjjDicK56tDNxlPQT4PJb9faBqV3+XZh+///fW2sbTL/RWxEppLpYJnyGY0eHpojV1hCh5sjQJcawQsAfnR3wE4fOr085aqvqiKpqd2Im9irriiFfnAh2FKJ1g6mIgew6wUpYyDegwpCXUfqbgiVC4LtE06TQBLpsiCMRqP2usAP/T2KH/bhPVqn/yd/1IExlDAk0QqCvJ9Zhe1Ob/Nhw62HJIb1xVGqS+bIbo5zTYHT4no+jeZmIqRmSqQh5FqXehH6/Cq9GjtYA1I13jg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
